# -*- coding: utf-8 -*-
"""Copy of Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Z7a9gVxwC8tZirJBkh8kq2st58xby5pn
"""

#get the password from user:
#from King_Parsa
a='1234235'
i=0
c=0
print('''Guess the password
You only have 6 chances to guess the correct password

=================================''')
while i==0:
  b=input('enter the password:')
  if len(a)!= len(b):
    print('the password has 7 charecter')
    c+=1
  elif c>=5:
    print('you`re blocked!')
    break
  elif a==b:
    print('welcome')
    i=1
  elif a!=b :
    print('try again')
    c+=1

#حدس عدد توسط کاربر
import random as rnd
b=rnd.randint(1,10)
i=0
c=0
print('''


Guess the correct number from zero to 10
You only have 3 chances

==================================================''')
while i==0:
  a=eval(input('enter your number:'))
  if a>b:
    c+=1
    if c<3:
      print('it`s lower than your number')
    else:
      print('you loss!')
      print(f'the number is {b}')
      break
  elif a<b:
     c+=1
     if c<3:
       print('it`s larger than your number')
     else:
       print('you loss!')
       print(f'the number is {b}')
       break
  else:
    print('nice!')
    i=1

